// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using user_manager_backend.Data;

#nullable disable

namespace user_manager_backend.Migrations
{
    [DbContext(typeof(UserDbContext))]
    partial class UserDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("user_management_backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 42,
                            Gender = "Male",
                            Name = "John Doe"
                        },
                        new
                        {
                            Id = 2,
                            Age = 21,
                            Gender = "Female",
                            Name = "Jane Doe"
                        },
                        new
                        {
                            Id = 3,
                            Age = 31,
                            Gender = "Female",
                            Name = "Jane Smith"
                        },
                        new
                        {
                            Id = 4,
                            Age = 34,
                            Gender = "Male",
                            Name = "John Smith"
                        },
                        new
                        {
                            Id = 5,
                            Age = 41,
                            Gender = "Male",
                            Name = "Eric Widget"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
